# Generated by Django 4.2 on 2023-05-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_paid_by', to='main_app.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_for',
            field=models.ManyToManyField(to='main_app.member'),
        ),
    ]
