# Generated by Django 4.2 on 2023-05-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_transaction_payer_transaction_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
