# Generated by Django 4.2 on 2023-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_member_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='individual_amt',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
